### ISSUE TITLE
stolen repo

### ISSUE THREAD

**Issue by sqlProvider** [MRebati/angular7-pubsub#1]
this repo steal from https://github.com/sqlProvider/angular2-pubsub

**Comment by MRebati** [comment]
I believe it was open source. I had issue with the pull requesting thing. so I cloned it. changed the RxJs versions which caused issue with angular 7 and added to the github. no interest in using it, so If you want to keep it, just clone and I will close this one. [also noted the credit of this project in the readme.md file in project back to the owner]

**Comment by sqlProvider** [comment]
delete this issue.

**Comment by MRebati** [comment]
by the way thanks for the great work
